POST http://localhost:3000/transactions
Content-Type: 'application/json'

{
  "title": "OP 05",
  "amount": 12458,
  "type": "credit"
}

###
GET http://localhost:3000/transactions

###
GET http://localhost:3000/transactions/summary

###
GET http://localhost:3000/transactions/0c1656bd-2b10-4f54-9441-dfe514adc12b